import { useCallback, useEffect, useState } from "preact/hooks";

interface EnvItem {
	key: string;
	value: string;
}

interface Preset {
	baseImage: string;
	workdir: string;
	installCmd: string;
	copyFiles: string;
	runCmd: string;
	port: string;
	envs: EnvItem[];
}

export default function DockerfileGenerator() {
	const [lang, setLang] = useState<"en" | "vi">("en");

	const presets: Record<string, Preset> = {
		node: {
			baseImage: "node:20-alpine",
			workdir: "/app",
			installCmd: "RUN npm ci --only=production",
			copyFiles: "COPY package*.json ./\nCOPY . .",
			runCmd: 'CMD ["npm", "start"]',
			port: "3000",
			envs: [{ key: "NODE_ENV", value: "production" }],
		},
		python: {
			baseImage: "python:3.11-slim",
			workdir: "/app",
			installCmd: "RUN pip install --no-cache-dir -r requirements.txt",
			copyFiles: "COPY requirements.txt ./\nCOPY . .",
			runCmd: 'CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]',
			port: "80",
			envs: [
				{ key: "PYTHONDONTWRITEBYTECODE", value: "1" },
				{ key: "PYTHONUNBUFFERED", value: "1" },
			],
		},
		go: {
			baseImage: "golang:1.21-alpine AS builder",
			workdir: "/app",
			installCmd: "RUN go mod download && RUN CGO_ENABLED=0 GOOS=linux go build -o main .",
			copyFiles: "COPY go.mod go.sum ./\nCOPY . .",
			runCmd: 'FROM alpine:latest\nWORKDIR /root/\nCOPY --from=builder /app/main .\nCMD ["./main"]',
			port: "8080",
			envs: [{ key: "GIN_MODE", value: "release" }],
		},
		php: {
			baseImage: "php:8.2-apache",
			workdir: "/var/www/html",
			installCmd: "RUN docker-php-ext-install pdo pdo_mysql",
			copyFiles: "COPY . .",
			runCmd: 'CMD ["apache2-foreground"]',
			port: "80",
			envs: [],
		},
		java: {
			baseImage: "eclipse-temurin:17-jdk-alpine AS build",
			workdir: "/workspace",
			installCmd: "RUN ./gradlew build -x test",
			copyFiles:
				"COPY gradlew .\nCOPY gradle gradle\nCOPY build.gradle settings.gradle ./\nCOPY src src",
			runCmd:
				'FROM eclipse-temurin:17-jre-alpine\nVOLUME /tmp\nCOPY --from=build /workspace/build/libs/*.jar app.jar\nENTRYPOINT ["java","-jar","/app.jar"]',
			port: "8888",
			envs: [],
		},
	};

	const [presetKey, setPresetKey] = useState<string>("node");
	const [baseImage, setBaseImage] = useState(presets.node.baseImage);
	const [workdir, setWorkdir] = useState(presets.node.workdir);
	const [installCmd, setInstallCmd] = useState(presets.node.installCmd);
	const [copyFiles, setCopyFiles] = useState(presets.node.copyFiles);
	const [runCmd, setRunCmd] = useState(presets.node.runCmd);
	const [port, setPort] = useState(presets.node.port);
	const [envs, setEnvs] = useState<EnvItem[]>(presets.node.envs);

	const [dockerfileText, setDockerfileText] = useState("");
	const [copied, setCopied] = useState(false);

	const t = {
		en: {
			title: "Dockerfile Generator",
			lblPreset: "Language Preset",
			lblBaseImage: "Base Docker Image (FROM)",
			lblWorkdir: "Working Directory (WORKDIR)",
			lblCopyFiles: "Files to Copy (COPY)",
			lblInstall: "Dependency Install Command",
			lblRun: "Run/Start Command (CMD / ENTRYPOINT)",
			lblPort: "Exposed Port (EXPOSE)",
			lblEnvs: "Environment Variables (ENV)",
			btnCopy: "Copy Dockerfile",
			copied: "Copied!",
			lblOutput: "Generated Dockerfile",
			btnAddEnv: "+ Add ENV",
			lblKey: "Key",
			lblValue: "Value",
		},
		vi: {
			title: "Trình tạo Dockerfile",
			lblPreset: "Mẫu ngôn ngữ / framework",
			lblBaseImage: "Ảnh Docker gốc (FROM)",
			lblWorkdir: "Thư mục làm việc (WORKDIR)",
			lblCopyFiles: "Sao chép tệp tin (COPY)",
			lblInstall: "Lệnh cài đặt thư viện/phụ thuộc",
			lblRun: "Lệnh khởi chạy (CMD / ENTRYPOINT)",
			lblPort: "Cổng mở (EXPOSE)",
			lblEnvs: "Biến môi trường (ENV)",
			btnCopy: "Sao chép Dockerfile",
			copied: "Đã copy!",
			lblOutput: "Tệp Dockerfile tạo ra",
			btnAddEnv: "+ Thêm biến ENV",
			lblKey: "Khóa",
			lblValue: "Giá trị",
		},
	}[lang];

	useEffect(() => {
		const savedLang = localStorage.getItem("toolbundle_lang");
		if (savedLang === "vi" || savedLang === "en") {
			setLang(savedLang as "vi" | "en");
		}
	}, []);

	const handlePresetChange = (key: string) => {
		setPresetKey(key);
		const p = presets[key];
		if (p) {
			setBaseImage(p.baseImage);
			setWorkdir(p.workdir);
			setInstallCmd(p.installCmd);
			setCopyFiles(p.copyFiles);
			setRunCmd(p.runCmd);
			setPort(p.port);
			setEnvs(p.envs);
		}
	};

	const generateDockerfile = useCallback(() => {
		let output = "";
		output += "# Generated by ToolBundle Dockerfile Generator\n\n";
		output += `FROM ${baseImage.trim()}\n\n`;

		if (workdir.trim()) {
			output += `WORKDIR ${workdir.trim()}\n\n`;
		}

		if (envs.length > 0) {
			for (const env of envs) {
				if (env.key.trim()) {
					output += `ENV ${env.key.trim()}="${env.value}"\n`;
				}
			}
			output += "\n";
		}

		if (copyFiles.trim()) {
			output += `${copyFiles.trim()}\n\n`;
		}

		if (installCmd.trim()) {
			output += `${installCmd.trim()}\n\n`;
		}

		if (port.trim()) {
			output += `EXPOSE ${port.trim()}\n\n`;
		}

		if (runCmd.trim()) {
			output += `${runCmd.trim()}\n`;
		}

		setDockerfileText(output);
	}, [baseImage, workdir, envs, copyFiles, installCmd, port, runCmd]);

	useEffect(() => {
		generateDockerfile();
	}, [generateDockerfile]);

	const handleAddEnv = () => {
		setEnvs([...envs, { key: "", value: "" }]);
	};

	const handleRemoveEnv = (index: number) => {
		setEnvs(envs.filter((_, i) => i !== index));
	};

	const handleEnvChange = (index: number, field: "key" | "value", val: string) => {
		setEnvs(
			envs.map((env, i) => {
				if (i === index) {
					return { ...env, [field]: val };
				}
				return env;
			}),
		);
	};

	const handleCopy = () => {
		navigator.clipboard.writeText(dockerfileText).then(() => {
			setCopied(true);
			setTimeout(() => setCopied(false), 2000);
		});
	};

	return (
		<div class="space-y-6">
			<div class="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
				{/* Builder Controls */}
				<div class="lg:col-span-6 bg-surface-elevated rounded-lg p-5 border border-hairline shadow-sm space-y-4">
					{/* Preset */}
					<div>
						<label class="text-body-sm-strong text-ink block mb-1.5">{t.lblPreset}</label>
						<select
							class="input w-full"
							value={presetKey}
							onChange={(e) => handlePresetChange((e.target as HTMLSelectElement).value)}
						>
							<option value="node">Node.js / React / Next.js</option>
							<option value="python">Python (FastAPI / Flask)</option>
							<option value="go">Go (Golang Alpine Build)</option>
							<option value="php">PHP / Apache</option>
							<option value="java">Java (Gradle Spring Boot)</option>
						</select>
					</div>

					{/* Base image */}
					<div>
						<label class="text-body-sm-strong text-ink block mb-1.5">{t.lblBaseImage}</label>
						<input
							type="text"
							class="input w-full font-mono text-body-sm"
							value={baseImage}
							onInput={(e) => setBaseImage((e.target as HTMLInputElement).value)}
						/>
					</div>

					{/* Workdir */}
					<div>
						<label class="text-body-sm-strong text-ink block mb-1.5">{t.lblWorkdir}</label>
						<input
							type="text"
							class="input w-full font-mono text-body-sm"
							value={workdir}
							onInput={(e) => setWorkdir((e.target as HTMLInputElement).value)}
						/>
					</div>

					{/* Environment Variables */}
					<div class="space-y-2">
						<div class="flex justify-between items-center">
							<span class="text-body-sm-strong text-ink">{t.lblEnvs}</span>
							<button class="btn-tertiary text-xs py-1" onClick={handleAddEnv}>
								{t.btnAddEnv}
							</button>
						</div>
						{envs.map((env, i) => (
							<div key={i} class="flex gap-2">
								<input
									type="text"
									class="input py-1 text-xs font-mono w-1/3"
									placeholder={t.lblKey}
									value={env.key}
									onInput={(e) => handleEnvChange(i, "key", (e.target as HTMLInputElement).value)}
								/>
								<input
									type="text"
									class="input py-1 text-xs font-mono flex-1"
									placeholder={t.lblValue}
									value={env.value}
									onInput={(e) => handleEnvChange(i, "value", (e.target as HTMLInputElement).value)}
								/>
								<button
									class="text-accent-rose hover:text-error-deep p-1.5"
									onClick={() => handleRemoveEnv(i)}
								>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="14"
										height="14"
										viewBox="0 0 24 24"
										fill="none"
										stroke="currentColor"
										stroke-width="2.5"
										stroke-linecap="round"
										stroke-linejoin="round"
									>
										<line x1="18" y1="6" x2="6" y2="18" />
										<line x1="6" y1="6" x2="18" y2="18" />
									</svg>
								</button>
							</div>
						))}
					</div>

					{/* Copy files */}
					<div>
						<label class="text-body-sm-strong text-ink block mb-1.5">{t.lblCopyFiles}</label>
						<textarea
							class="textarea w-full font-mono text-body-sm"
							style={{ minHeight: "60px" }}
							value={copyFiles}
							onInput={(e) => setCopyFiles((e.target as HTMLTextAreaElement).value)}
						/>
					</div>

					{/* Install dependencies */}
					<div>
						<label class="text-body-sm-strong text-ink block mb-1.5">{t.lblInstall}</label>
						<input
							type="text"
							class="input w-full font-mono text-body-sm"
							value={installCmd}
							onInput={(e) => setInstallCmd((e.target as HTMLInputElement).value)}
						/>
					</div>

					{/* Port */}
					<div>
						<label class="text-body-sm-strong text-ink block mb-1.5">{t.lblPort}</label>
						<input
							type="text"
							class="input w-full font-mono text-body-sm"
							value={port}
							onInput={(e) => setPort((e.target as HTMLInputElement).value)}
						/>
					</div>

					{/* Run Cmd */}
					<div>
						<label class="text-body-sm-strong text-ink block mb-1.5">{t.lblRun}</label>
						<textarea
							class="textarea w-full font-mono text-body-sm"
							style={{ minHeight: "60px" }}
							value={runCmd}
							onInput={(e) => setRunCmd((e.target as HTMLTextAreaElement).value)}
						/>
					</div>
				</div>

				{/* Output Panel */}
				<div class="lg:col-span-6 bg-surface-elevated rounded-lg p-5 border border-hairline shadow-sm space-y-4">
					<div class="flex justify-between items-center">
						<label class="text-body-sm-strong text-ink">{t.lblOutput}</label>
						<button
							class="btn-secondary py-1 px-3 text-xs flex items-center gap-1.5 active:scale-[0.98] transition-all cursor-pointer font-bold rounded-full"
							onClick={handleCopy}
						>
							{copied ? (
								<>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="12"
										height="12"
										viewBox="0 0 24 24"
										fill="none"
										stroke="var(--color-accent-emerald)"
										stroke-width="3"
										stroke-linecap="round"
										stroke-linejoin="round"
									>
										<polyline points="20 6 9 17 4 12" />
									</svg>
									{t.copied}
								</>
							) : (
								<>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="12"
										height="12"
										viewBox="0 0 24 24"
										fill="none"
										stroke="currentColor"
										stroke-width="2.5"
										stroke-linecap="round"
										stroke-linejoin="round"
									>
										<rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
										<path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
									</svg>
									{t.btnCopy}
								</>
							)}
						</button>
					</div>
					<textarea
						class="textarea font-mono text-body-sm w-full bg-surface-soft"
						style={{ minHeight: "530px" }}
						readOnly
						value={dockerfileText}
					/>
				</div>
			</div>
		</div>
	);
}
