import { useCallback, useEffect, useState } from "preact/hooks";

export default function HtaccessGenerator() {
	const [lang, setLang] = useState<"en" | "vi">("en");

	// Basic Redirects
	const [forceHttps, setForceHttps] = useState(false);
	const [wwwMode, setWwwMode] = useState<"none" | "force-www" | "force-non-www">("none");

	// Directory Listing
	const [disableIndex, setDisableIndex] = useState(true);

	// Custom Error Documents
	const [error404, setError404] = useState("/404.html");
	const [error500, setError500] = useState("/500.html");

	// Caching
	const [enableCaching, setEnableCaching] = useState(true);

	// Block IPs
	const [blockIps, setBlockIps] = useState("");

	const [htaccessText, setHtaccessText] = useState("");
	const [copied, setCopied] = useState(false);

	const t = {
		en: {
			title: ".htaccess Generator",
			lblHttps: "Force HTTPS Redirect",
			lblWww: "WWW Redirection",
			optWwwNone: "No redirection",
			optWwwForce: "Force www prefix (http://example.com -> http://www.example.com)",
			optWwwRemove: "Remove www prefix (http://www.example.com -> http://example.com)",
			lblDisableIndex: "Disable Directory Indexing (Options -Indexes)",
			lblErrorDocs: "Custom Error Documents",
			lblCaching: "Enable Browser Caching (ExpiresActive On)",
			lblBlockIps: "Block specific IP addresses (comma separated)",
			btnCopy: "Copy .htaccess Config",
			copied: "Copied!",
			lblOutput: "Generated .htaccess Content",
			redirectsTab: "Redirects",
			securityTab: "Security",
			performanceTab: "Performance",
		},
		vi: {
			title: "Trình tạo tệp .htaccess",
			lblHttps: "Tự động chuyển hướng sang HTTPS",
			lblWww: "Định dạng WWW",
			optWwwNone: "Không chuyển hướng",
			optWwwForce: "Bắt buộc có tiền tố www (http://example.com -> http://www.example.com)",
			optWwwRemove: "Loại bỏ tiền tố www (http://www.example.com -> http://example.com)",
			lblDisableIndex: "Không cho phép liệt kê thư mục (Options -Indexes)",
			lblErrorDocs: "Tùy chọn trang báo lỗi hệ thống",
			lblCaching: "Kích hoạt bộ nhớ đệm trình duyệt (Browser Caching)",
			lblBlockIps: "Chặn danh sách địa chỉ IP (cách nhau bằng dấu phẩy)",
			btnCopy: "Sao chép mã .htaccess",
			copied: "Đã copy!",
			lblOutput: "Nội dung tệp .htaccess tạo ra",
			redirectsTab: "Chuyển hướng (Redirects)",
			securityTab: "Bảo mật",
			performanceTab: "Hiệu năng",
		},
	}[lang];

	useEffect(() => {
		const savedLang = localStorage.getItem("toolbundle_lang");
		if (savedLang === "vi" || savedLang === "en") {
			setLang(savedLang as "vi" | "en");
		}
	}, []);

	const generateHtaccess = useCallback(() => {
		let ht = "# Generated by ToolBundle .htaccess Generator\n\n";

		// Rewrite Engine start
		if (forceHttps || wwwMode !== "none") {
			ht += "<IfModule mod_rewrite.c>\n";
			ht += "    RewriteEngine On\n";
			ht += "    RewriteBase /\n\n";

			if (forceHttps) {
				ht += "    # Force HTTPS\n";
				ht += "    RewriteCond %{HTTPS} off\n";
				ht += "    RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]\n\n";
			}

			if (wwwMode === "force-www") {
				ht += "    # Force WWW\n";
				ht += "    RewriteCond %{HTTP_HOST} !^www\\. [NC]\n";
				ht += "    RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]\n\n";
			} else if (wwwMode === "force-non-www") {
				ht += "    # Remove WWW\n";
				ht += "    RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]\n";
				ht += "    RewriteRule ^(.*)$ http://%1/$1 [R=301,L]\n\n";
			}

			ht += "</IfModule>\n\n";
		}

		// Security: Directory Listing
		if (disableIndex) {
			ht += "# Disable Directory Listings\n";
			ht += "Options -Indexes\n\n";
		}

		// Security: Block IPs
		if (blockIps.trim()) {
			ht += "# Block Bad IP Addresses\n";
			ht += "<RequireAll>\n";
			ht += "    Require all granted\n";
			const ips = blockIps.split(",");
			for (const ip of ips) {
				if (ip.trim()) {
					ht += `    Require not ip ${ip.trim()}\n`;
				}
			}
			ht += "</RequireAll>\n\n";
		}

		// Custom Error Pages
		if (error404.trim() || error500.trim()) {
			ht += "# Custom Error Documents\n";
			if (error404.trim()) {
				ht += `ErrorDocument 404 ${error404.trim()}\n`;
			}
			if (error500.trim()) {
				ht += `ErrorDocument 500 ${error500.trim()}\n`;
			}
			ht += "\n";
		}

		// Performance: Browser caching
		if (enableCaching) {
			ht += "# Enable Browser Caching (Expires Headers)\n";
			ht += "<IfModule mod_expires.c>\n";
			ht += "    ExpiresActive On\n";
			ht += `    ExpiresDefault "access plus 1 month"\n`;
			ht += `    ExpiresByType image/jpg "access plus 1 year"\n`;
			ht += `    ExpiresByType image/jpeg "access plus 1 year"\n`;
			ht += `    ExpiresByType image/gif "access plus 1 year"\n`;
			ht += `    ExpiresByType image/png "access plus 1 year"\n`;
			ht += `    ExpiresByType text/css "access plus 1 month"\n`;
			ht += `    ExpiresByType application/pdf "access plus 1 month"\n`;
			ht += `    ExpiresByType text/javascript "access plus 1 month"\n`;
			ht += `    ExpiresByType application/javascript "access plus 1 month"\n`;
			ht += `    ExpiresByType application/x-javascript "access plus 1 month"\n`;
			ht += `    ExpiresByType image/x-icon "access plus 1 year"\n`;
			ht += "</IfModule>\n";
		}

		setHtaccessText(ht);
	}, [forceHttps, wwwMode, disableIndex, error404, error500, enableCaching, blockIps]);

	useEffect(() => {
		generateHtaccess();
	}, [generateHtaccess]);

	const handleCopy = () => {
		navigator.clipboard.writeText(htaccessText).then(() => {
			setCopied(true);
			setTimeout(() => setCopied(false), 2000);
		});
	};

	return (
		<div class="space-y-6">
			<div class="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
				{/* Settings Controls */}
				<div class="lg:col-span-6 bg-surface-elevated rounded-lg p-5 border border-hairline shadow-sm space-y-5">
					{/* Redirects */}
					<div class="space-y-3 pb-3 border-b border-hairline">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">{t.redirectsTab}</h3>
						<div>
							<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
								<input
									type="checkbox"
									class="accent-primary"
									checked={forceHttps}
									onChange={(e) => setForceHttps((e.target as HTMLInputElement).checked)}
								/>
								{t.lblHttps}
							</label>
						</div>
						<div class="space-y-1.5">
							<label class="text-body-sm-strong text-ink block">{t.lblWww}</label>
							<select
								class="input w-full"
								value={wwwMode}
								onChange={(e) =>
									setWwwMode((e.target as HTMLSelectElement).value as typeof wwwMode)
								}
							>
								<option value="none">{t.optWwwNone}</option>
								<option value="force-www">{t.optWwwForce}</option>
								<option value="force-non-www">{t.optWwwRemove}</option>
							</select>
						</div>
					</div>

					{/* Security */}
					<div class="space-y-3 pb-3 border-b border-hairline">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">{t.securityTab}</h3>
						<div>
							<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
								<input
									type="checkbox"
									class="accent-primary"
									checked={disableIndex}
									onChange={(e) => setDisableIndex((e.target as HTMLInputElement).checked)}
								/>
								{t.lblDisableIndex}
							</label>
						</div>
						<div>
							<label class="text-body-sm-strong text-ink block mb-1">{t.lblBlockIps}</label>
							<input
								type="text"
								class="input w-full font-mono text-body-sm"
								placeholder="e.g. 1.2.3.4, 5.6.7.8"
								value={blockIps}
								onInput={(e) => setBlockIps((e.target as HTMLInputElement).value)}
							/>
						</div>
					</div>

					{/* Custom Errors */}
					<div class="space-y-3 pb-3 border-b border-hairline">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">{t.lblErrorDocs}</h3>
						<div class="grid grid-cols-2 gap-4">
							<div>
								<label class="text-body-sm-strong text-ink block mb-1">404 Error Page</label>
								<input
									type="text"
									class="input w-full font-mono text-body-sm"
									value={error404}
									onInput={(e) => setError404((e.target as HTMLInputElement).value)}
								/>
							</div>
							<div>
								<label class="text-body-sm-strong text-ink block mb-1">500 Error Page</label>
								<input
									type="text"
									class="input w-full font-mono text-body-sm"
									value={error500}
									onInput={(e) => setError500((e.target as HTMLInputElement).value)}
								/>
							</div>
						</div>
					</div>

					{/* Performance */}
					<div class="space-y-3">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">
							{t.performanceTab}
						</h3>
						<div>
							<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
								<input
									type="checkbox"
									class="accent-primary"
									checked={enableCaching}
									onChange={(e) => setEnableCaching((e.target as HTMLInputElement).checked)}
								/>
								{t.lblCaching}
							</label>
						</div>
					</div>
				</div>

				{/* Output Panel */}
				<div class="lg:col-span-6 bg-surface-elevated rounded-lg p-5 border border-hairline shadow-sm space-y-4">
					<div class="flex justify-between items-center">
						<label class="text-body-sm-strong text-ink">{t.lblOutput}</label>
						<button
							class="btn-secondary py-1 px-3 text-xs flex items-center gap-1.5 active:scale-[0.98] transition-all cursor-pointer font-bold rounded-full"
							onClick={handleCopy}
						>
							{copied ? (
								<>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="12"
										height="12"
										viewBox="0 0 24 24"
										fill="none"
										stroke="var(--color-accent-emerald)"
										stroke-width="3"
										stroke-linecap="round"
										stroke-linejoin="round"
									>
										<polyline points="20 6 9 17 4 12" />
									</svg>
									{t.copied}
								</>
							) : (
								<>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="12"
										height="12"
										viewBox="0 0 24 24"
										fill="none"
										stroke="currentColor"
										stroke-width="2.5"
										stroke-linecap="round"
										stroke-linejoin="round"
									>
										<rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
										<path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
									</svg>
									{t.btnCopy}
								</>
							)}
						</button>
					</div>
					<textarea
						class="textarea font-mono text-body-sm w-full bg-surface-soft"
						style={{ minHeight: "450px" }}
						readOnly
						value={htaccessText}
					/>
				</div>
			</div>
		</div>
	);
}
