import { useCallback, useEffect, useState } from "preact/hooks";

export default function NginxGenerator() {
	const [lang, setLang] = useState<"en" | "vi">("en");

	// Basic configs
	const [domains, setDomains] = useState("example.com www.example.com");
	const [port, setPort] = useState("80");
	const [rootPath, setRootPath] = useState("/var/www/html");
	const [indexFiles, setIndexFiles] = useState("index.html index.htm");

	// Proxy
	const [enableProxy, setEnableProxy] = useState(false);
	const [proxyPass, setProxyPass] = useState("http://127.0.0.1:3000");

	// SSL
	const [enableSsl, setEnableSsl] = useState(false);
	const [sslPort, setSslPort] = useState("443");
	const [sslCert, setSslCert] = useState("/etc/letsencrypt/live/example.com/fullchain.pem");
	const [sslKey, setSslKey] = useState("/etc/letsencrypt/live/example.com/privkey.pem");
	const [forceHttps, setForceHttps] = useState(false);

	// Gzip
	const [enableGzip, setEnableGzip] = useState(true);

	// SPA Routing
	const [enableSpa, setEnableSpa] = useState(false);

	const [configText, setConfigText] = useState("");
	const [copied, setCopied] = useState(false);

	const t = {
		en: {
			title: "Nginx Config Generator",
			lblDomains: "Domain Names (space separated)",
			lblPort: "HTTP Port",
			lblRoot: "Root Directory path",
			lblIndex: "Index Files",
			lblProxy: "Enable Reverse Proxy",
			lblProxyPass: "Proxy Pass Target",
			lblSsl: "Enable SSL / HTTPS",
			lblSslPort: "HTTPS Port",
			lblCert: "SSL Certificate Path",
			lblKey: "SSL Certificate Key Path",
			lblForceHttps: "Force HTTP to HTTPS redirect",
			lblGzip: "Enable Gzip compression",
			lblSpa: "Single Page Application (SPA) Routing",
			btnCopy: "Copy Nginx Config",
			copied: "Copied!",
			lblOutput: "Generated Nginx Config",
			basicTab: "Basic Config",
			proxyTab: "Reverse Proxy",
			sslTab: "SSL & Security",
			optTab: "Optimizations",
		},
		vi: {
			title: "Trình tạo cấu hình Nginx",
			lblDomains: "Tên miền (cách nhau bằng dấu cách)",
			lblPort: "Cổng HTTP",
			lblRoot: "Thư mục Root ứng dụng",
			lblIndex: "Tệp tin index mặc định",
			lblProxy: "Kích hoạt Reverse Proxy (Ủy quyền ngược)",
			lblProxyPass: "Địa chỉ chuyển tiếp (Proxy Pass)",
			lblSsl: "Kích hoạt cấu hình SSL / HTTPS",
			lblSslPort: "Cổng HTTPS",
			lblCert: "Đường dẫn Tệp tin SSL Certificate",
			lblKey: "Đường dẫn Tệp tin SSL Private Key",
			lblForceHttps: "Tự động chuyển HTTP sang HTTPS",
			lblGzip: "Kích hoạt nén dữ liệu Gzip",
			lblSpa: "Hỗ trợ định tuyến Single Page Application (SPA)",
			btnCopy: "Sao chép cấu hình Nginx",
			copied: "Đã copy!",
			lblOutput: "Cấu hình Nginx tạo ra",
			basicTab: "Cấu hình Cơ bản",
			proxyTab: "Reverse Proxy",
			sslTab: "Cấu hình SSL",
			optTab: "Tối ưu hóa",
		},
	}[lang];

	useEffect(() => {
		const savedLang = localStorage.getItem("toolbundle_lang");
		if (savedLang === "vi" || savedLang === "en") {
			setLang(savedLang as "vi" | "en");
		}
	}, []);

	const generateConfig = useCallback(() => {
		let conf = "# Generated by ToolBundle Nginx Configuration Generator\n\n";

		// HTTP redirect to HTTPS
		if (enableSsl && forceHttps) {
			conf += "server {\n";
			conf += `    listen ${port};\n`;
			conf += `    server_name ${domains.trim() || "localhost"};\n`;
			conf += "    return 301 https://$host$request_uri;\n";
			conf += "}\n\n";
		}

		conf += "server {\n";

		if (enableSsl) {
			conf += `    listen ${sslPort} ssl;\n`;
			if (!forceHttps) {
				conf += `    listen ${port};\n`;
			}
			conf += `    server_name ${domains.trim() || "localhost"};\n\n`;

			conf += "    # SSL Certificate Settings\n";
			conf += `    ssl_certificate ${sslCert.trim()};\n`;
			conf += `    ssl_certificate_key ${sslKey.trim()};\n`;
			conf += "    ssl_protocols TLSv1.2 TLSv1.3;\n";
			conf += "    ssl_ciphers HIGH:!aNULL:!MD5;\n";
			conf += "    ssl_prefer_server_ciphers on;\n\n";
		} else {
			conf += `    listen ${port};\n`;
			conf += `    server_name ${domains.trim() || "localhost"};\n\n`;
		}

		conf += "    # App Root\n";
		conf += `    root ${rootPath.trim()};\n`;
		conf += `    index ${indexFiles.trim()};\n\n`;

		if (enableGzip) {
			conf += "    # Gzip Compression\n";
			conf += "    gzip on;\n";
			conf +=
				"    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;\n";
			conf += "    gzip_min_length 1000;\n\n";
		}

		// Main Location block
		conf += "    # Request Routing\n";
		conf += "    location / {\n";
		if (enableProxy) {
			conf += `        proxy_pass ${proxyPass.trim()};\n`;
			conf += "        proxy_http_version 1.1;\n";
			conf += "        proxy_set_header Upgrade $http_upgrade;\n";
			conf += `        proxy_set_header Connection 'upgrade';\n`;
			conf += "        proxy_set_header Host $host;\n";
			conf += "        proxy_cache_bypass $http_upgrade;\n";
			conf += "        proxy_set_header X-Real-IP $remote_addr;\n";
			conf += "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n";
			conf += "        proxy_set_header X-Forwarded-Proto $scheme;\n";
		} else if (enableSpa) {
			conf += "        try_files $uri $uri/ /index.html;\n";
		} else {
			conf += "        try_files $uri $uri/ =404;\n";
		}
		conf += "    }\n\n";

		// Security Headers
		conf += "    # Security Headers\n";
		conf += `    add_header X-Frame-Options "SAMEORIGIN" always;\n`;
		conf += `    add_header X-XSS-Protection "1; mode=block" always;\n`;
		conf += `    add_header X-Content-Type-Options "nosniff" always;\n`;
		conf += `    add_header Referrer-Policy "no-referrer-when-downgrade" always;\n`;
		conf += `    add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;\n`;

		conf += "}\n";

		setConfigText(conf);
	}, [
		domains,
		port,
		rootPath,
		indexFiles,
		enableProxy,
		proxyPass,
		enableSsl,
		sslPort,
		sslCert,
		sslKey,
		forceHttps,
		enableGzip,
		enableSpa,
	]);

	useEffect(() => {
		generateConfig();
	}, [generateConfig]);

	const handleCopy = () => {
		navigator.clipboard.writeText(configText).then(() => {
			setCopied(true);
			setTimeout(() => setCopied(false), 2000);
		});
	};

	return (
		<div class="space-y-6">
			<div class="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
				{/* Configuration Controllers */}
				<div class="lg:col-span-6 bg-surface-elevated rounded-lg p-5 border border-hairline shadow-sm space-y-5">
					{/* Basic tab config */}
					<div class="space-y-3 pb-3 border-b border-hairline">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">{t.basicTab}</h3>
						<div>
							<label class="text-body-sm-strong text-ink block mb-1">{t.lblDomains}</label>
							<input
								type="text"
								class="input w-full font-mono text-body-sm"
								value={domains}
								onInput={(e) => setDomains((e.target as HTMLInputElement).value)}
							/>
						</div>
						<div class="grid grid-cols-2 gap-4">
							<div>
								<label class="text-body-sm-strong text-ink block mb-1">{t.lblPort}</label>
								<input
									type="text"
									class="input w-full font-mono text-body-sm"
									value={port}
									onInput={(e) => setPort((e.target as HTMLInputElement).value)}
								/>
							</div>
							<div>
								<label class="text-body-sm-strong text-ink block mb-1">{t.lblIndex}</label>
								<input
									type="text"
									class="input w-full font-mono text-body-sm"
									value={indexFiles}
									onInput={(e) => setIndexFiles((e.target as HTMLInputElement).value)}
								/>
							</div>
						</div>
						<div>
							<label class="text-body-sm-strong text-ink block mb-1">{t.lblRoot}</label>
							<input
								type="text"
								class="input w-full font-mono text-body-sm"
								value={rootPath}
								onInput={(e) => setRootPath((e.target as HTMLInputElement).value)}
							/>
						</div>
					</div>

					{/* Reverse proxy configs */}
					<div class="space-y-3 pb-3 border-b border-hairline">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">{t.proxyTab}</h3>
						<div>
							<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
								<input
									type="checkbox"
									class="accent-primary"
									checked={enableProxy}
									onChange={(e) => setEnableProxy((e.target as HTMLInputElement).checked)}
								/>
								{t.lblProxy}
							</label>
						</div>
						{enableProxy && (
							<div>
								<label class="text-body-sm-strong text-ink block mb-1">{t.lblProxyPass}</label>
								<input
									type="text"
									class="input w-full font-mono text-body-sm"
									value={proxyPass}
									onInput={(e) => setProxyPass((e.target as HTMLInputElement).value)}
								/>
							</div>
						)}
					</div>

					{/* SSL tab config */}
					<div class="space-y-3 pb-3 border-b border-hairline">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">{t.sslTab}</h3>
						<div>
							<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
								<input
									type="checkbox"
									class="accent-primary"
									checked={enableSsl}
									onChange={(e) => setEnableSsl((e.target as HTMLInputElement).checked)}
								/>
								{t.lblSsl}
							</label>
						</div>
						{enableSsl && (
							<div class="space-y-3 pt-2">
								<div>
									<label class="text-body-sm-strong text-ink block mb-1">{t.lblSslPort}</label>
									<input
										type="text"
										class="input w-full font-mono text-body-sm"
										value={sslPort}
										onInput={(e) => setSslPort((e.target as HTMLInputElement).value)}
									/>
								</div>
								<div>
									<label class="text-body-sm-strong text-ink block mb-1">{t.lblCert}</label>
									<input
										type="text"
										class="input w-full font-mono text-body-sm"
										value={sslCert}
										onInput={(e) => setSslCert((e.target as HTMLInputElement).value)}
									/>
								</div>
								<div>
									<label class="text-body-sm-strong text-ink block mb-1">{t.lblKey}</label>
									<input
										type="text"
										class="input w-full font-mono text-body-sm"
										value={sslKey}
										onInput={(e) => setSslKey((e.target as HTMLInputElement).value)}
									/>
								</div>
								<div>
									<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
										<input
											type="checkbox"
											class="accent-primary"
											checked={forceHttps}
											onChange={(e) => setForceHttps((e.target as HTMLInputElement).checked)}
										/>
										{t.lblForceHttps}
									</label>
								</div>
							</div>
						)}
					</div>

					{/* Optimizations */}
					<div class="space-y-3">
						<h3 class="text-xs text-muted font-bold uppercase tracking-wider">{t.optTab}</h3>
						<div class="space-y-2">
							<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
								<input
									type="checkbox"
									class="accent-primary"
									checked={enableGzip}
									onChange={(e) => setEnableGzip((e.target as HTMLInputElement).checked)}
								/>
								{t.lblGzip}
							</label>
							{!enableProxy && (
								<label class="flex items-center gap-2 text-xs font-bold text-ink cursor-pointer">
									<input
										type="checkbox"
										class="accent-primary"
										checked={enableSpa}
										onChange={(e) => setEnableSpa((e.target as HTMLInputElement).checked)}
									/>
									{t.lblSpa}
								</label>
							)}
						</div>
					</div>
				</div>

				{/* Output Nginx Config */}
				<div class="lg:col-span-6 bg-surface-elevated rounded-lg p-5 border border-hairline shadow-sm space-y-4">
					<div class="flex justify-between items-center">
						<label class="text-body-sm-strong text-ink">{t.lblOutput}</label>
						<button
							class="btn-secondary py-1 px-3 text-xs flex items-center gap-1.5 active:scale-[0.98] transition-all cursor-pointer font-bold rounded-full"
							onClick={handleCopy}
						>
							{copied ? (
								<>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="12"
										height="12"
										viewBox="0 0 24 24"
										fill="none"
										stroke="var(--color-accent-emerald)"
										stroke-width="3"
										stroke-linecap="round"
										stroke-linejoin="round"
									>
										<polyline points="20 6 9 17 4 12" />
									</svg>
									{t.copied}
								</>
							) : (
								<>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="12"
										height="12"
										viewBox="0 0 24 24"
										fill="none"
										stroke="currentColor"
										stroke-width="2.5"
										stroke-linecap="round"
										stroke-linejoin="round"
									>
										<rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
										<path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
									</svg>
									{t.btnCopy}
								</>
							)}
						</button>
					</div>
					<textarea
						class="textarea font-mono text-body-sm w-full bg-surface-soft"
						style={{ minHeight: "530px" }}
						readOnly
						value={configText}
					/>
				</div>
			</div>
		</div>
	);
}
